# Generated by Django 4.1 on 2023-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admission",
        ),
        migrations.RemoveField(
            model_name="coursevideo",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="user_profile",
        ),
        migrations.DeleteModel(
            name="OrderUpdate",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.AddField(
            model_name="courselimage",
            name="button_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="courselimage",
            name="sub_title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="courselimage",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="CourseVideo",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
