# Generated by Django 4.1 on 2023-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduapp", "0004_remove_enrollment_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="id",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
