# Generated by Django 4.1 on 2023-09-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduapp", "0009_studentexamassociation_quiz_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexamassociation",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
